[package]
name = "yetanotherclown/planck"
description = "An Agnostic Scheduler for ECS"
license = "MIT"
authors = ["YetAnotherClown"]
version = "0.2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
homepage = "https://yetanotherclown.github.io/planck"
repository = "https://github.com/yetanotherclown/planck"

exclude = [
    "tests",
    "tests/*",
    "run-tests.server.luau",
    "src/__*__",
    "src/__*__/*",
    "src/jest.config.luau",
    "package.json",
    "*.tgz",
    "*.zip",
]
include = ["wally.lock"]

[dev-dependencies]
Jest = "jsdotlua/jest@3.6.1-rc.2"
JestGlobals = "jsdotlua/jest-globals@3.6.1-rc.2"
