return {
    Lyrical = { 
        displayName = "LiriliriLarila",
        rarity = "Rare",

        moneyPerTime = 50,
        timeInterval = 3,
        speed = 10,

        animationIds = {
            walking = 110307197758476,
            idle = 128189080030224,
            running = 109891408716798,
            freakOut = 87908618423120,
        }
    },
    Trails = { 
        displayName = "Tralalerito",
        rarity = "Rare",

        moneyPerTime = 50,
        timeInterval = 3,
        speed = 10,

        animationIds = {
            walking = 91962543063609,
            idle = 70965180987131,
            running = 107186157226136,
            freakOut = 76417905912309,
        }
    },
    Tripper = { 
        displayName = "Trippi Troppi",
        rarity = "Rare",

        moneyPerTime = 50,
        timeInterval = 3,
        speed = 10,

        animationIds = {
            walking = 123391351527542,
            idle = 114762734106339,
            running = 125712526747426,
            freakOut = 117844592563711,
        }
    },
    Catfish = {
        displayName = "Trippi Catfish",
        rarity = "Rare",

        moneyPerTime = 50,
        timeInterval = 3,
        speed = 10,

        animationIds = {
            walking = 78015957592401,
            idle = 100216616357315,
            running = 125644976966648,
            freakOut = 97951814190971,
        }
    },
    OrangutanPineapple = { 
        displayName = "Orangutini Ananassini",
        rarity = "Rare",

        moneyPerTime = 50,
        timeInterval = 3,
        speed = 10,

        animationIds = {
            walking = 78853989543463,
            idle = 121657846536847,
            running = 80821364505831,
            freakOut = 115354431316961,
        }
    },
    CoffeeKiller = { 
        displayName = "Cappuccino Assassino",
        rarity = "Rare",

        moneyPerTime = 50,
        timeInterval = 3,
        speed = 10,

        animationIds = {
            walking = 130323315565345,
            idle = 72116864551204,
            running = 104871090511786,
            freakOut = 88962136289463,
        }
    },
    BananaDolphin = { 
        displayName = "Bananita Dolphinita",
        rarity = "Rare",

        moneyPerTime = 50,
        timeInterval = 3,
        speed = 10,

        animationIds = {
            walking = 86267194714834,
            idle = 103543627947972,
            running = 108401867614916,
            freakOut = 79424184326957,
        }
    },
    BombCroc = { 
        displayName = "Bombardiro Crocodilo",
        rarity = "Rare",

        moneyPerTime = 50,
        timeInterval = 3,
        speed = 10,

        animationIds = {
            walking = 1,
            idle = 1,
            running = 1,
            freakOut = 1,
        }
    },
    BombGeese = { 
        displayName = "Bombardini Gusini",
        rarity = "Rare",

        moneyPerTime = 50,
        timeInterval = 3,
        speed = 10,

        animationIds = {
            walking = 1,
            idle = 1,
            running = 1,
            freakOut = 1,
        }
    },
    ChimpBanana = { 
        displayName = "Chimpanzini Bananini",
        rarity = "Rare",

        moneyPerTime = 50,
        timeInterval = 3,
        speed = 10,

        animationIds = {
            walking = 138116715873700,
            idle = 137758277116634,
            running = 92901363671606,
            freakOut = 112638537966551,
        }
    },
    SharkShoes = { 
        displayName = "Tralalero Tralala",
        rarity = "Rare",

        moneyPerTime = 50,
        timeInterval = 3,
        speed = 10,

        animationIds = {
            walking = 70536139692319,
            idle = 119087511773724,
            running = 125250620918579,
            freakOut = 113923490505819,
        }
    },
    Teapot = { 
        displayName = "Ta ta ta ta sahur",
        rarity = "Rare",

        moneyPerTime = 50,
        timeInterval = 3,
        speed = 10,

        animationIds = {
            walking = 90491856847321,
            idle = 130491637335795,
            running = 118588174909118,
            freakOut = 105450399553239,
        }
    },
    AlegatorBall = { 
        displayName = "Glorbo Fruttodrillo",
        rarity = "Rare",

        moneyPerTime = 50,
        timeInterval = 3,
        speed = 10,
        
        animationIds = {
            walking = 85004228673604,
            idle = 131196487471246,
            running = 110039888029015,
            freakOut = 140677535972440,
        }
    },

    TrueLemons = { 
        displayName = "Trulimero Trulicina",
        rarity = "Rare",

        moneyPerTime = 50,
        timeInterval = 3,
        speed = 10,

        animationIds = {
            walking = 1,
            idle = 1,
            running = 1,
            freakOut = 1,
        }
    },
    BalletCup = { 
        displayName = "Ballerina Cappucina",
        rarity = "Rare",

        moneyPerTime = 50,
        timeInterval = 3,
        speed = 10,

        animationIds = {
            walking = 1,
            idle = 1,
            running = 1,
            freakOut = 1,
        }
    },
}
