return {
    Tools = {
        BigHand = {
            displayName = "The Big Hand",
            price = 2000,
            robuxPrice = 27,
            description = "Make players fly easier with more distance to hit.",
            imageId = "rbxassetid://109841249769996",
            gamepassId = 1411364564,
        },
        SpeedCoil = {
            displayName = "Speed & Jump Coil",
            price = 4000,
            robuxPrice = 37,
            description = "Run higher and jump faster.",
            imageId = "rbxassetid://116848878734828",
            gamepassId = 1412076351,
        }
    }
}