return {
    Tools = {
        TheClapHand = {
            displayName = "The Clap Hand",
            price = 2000,
            robuxPrice = 27,
            description = "Make players fly across the map.",
            imageId = "rbxassetid://15588301798",
            gamepassId = 1,
        },
        SpeedCoil = {
            displayName = "Speed & Jump Coil",
            price = 4000,
            robuxPrice = 37,
            description = "Run higher and jump faster.",
            imageId = "http://www.roblox.com/asset/?id=1059024026",
            gamepassId = 1,
        }
    }
}